Trollheim and Weiss Region overhaul
117HD/RLHD pull request #261
Opened 2023-10-17 23:34 UTC by SirFancyBacon

Overhauls the Trollheim and Weiss region:
* Remove Normals from vertical dirt to avoid ugly Normals around Trollheim
* Retextures Trollheim with a different Grunge material
* Apply materials to objects missing materials such as rocks, detritus, doors, ladders, walls coffins, etc
* Apply Winter Cobblestone for cobble in Weiss
* Newly generated normals and improved displacement map for Cobblestone
* Replace all snow textures with matching source ones from AmbientCG

![image](https://github.com/117HD/RLHD/assets/11658143/e27dc219-2608-4259-9c0b-a2a9add29c54)

2023-10-22 04:08 UTC, aHooder requested changes
I think this snow looks too patchy with those dark spots, and the normals could do with more finer detail ideally:
![image](https://github.com/117HD/RLHD/assets/831317/6706bb28-c3aa-4cf9-beea-1cd42631d0d5)

I didn't notice the jagged stone displacement at first, but it looks pretty nice and subtle :slightly_smiling_face: 

The entrance light looks a bit too blown out, but I do like the look a lot otherwise: 
![image](https://github.com/117HD/RLHD/assets/831317/e1b0865e-fcd3-4931-bab4-6542a7d64b2f)

I like pretty much all of the other lighting you've added :slightly_smiling_face: 

I unfortunately can't look through any of the stuff in the quest area. Did you change anything there?

2023-10-22 04:08 UTC, aHooder commented on src/main/java/rs117/hd/data/materials/Material.java
> +	GRUNGE_2_TROLLHEIM_WALL_FIX_2(GRUNGE_2, p -> p.setBrightness(1.2f)),
I think it might be good to instead add functionality for this with model overrides, so we don't need a lot of duplicate materials for fixes like these.

2023-10-22 04:12 UTC, SirFancyBacon commented on src/main/java/rs117/hd/data/materials/Material.java
> +	GRUNGE_2_TROLLHEIM_WALL_FIX_2(GRUNGE_2, p -> p.setBrightness(1.2f)),
Absolutely that would be fantastic! though if we could simply stop whatever is causing the darkness of the object that would be awesome too; Sometimes it is the model; But it's almost like Jagex used dynamic baked lighting on the models in the Troll stronghold; Same model but different levels of darkness

2023-10-22 04:13 UTC, SirFancyBacon commented
> I think this snow looks too patchy with those dark spots, and the normals could do with more finer detail ideally: ![image](https://user-images.githubusercontent.com/831317/277144635-6706bb28-c3aa-4cf9-beea-1cd42631d0d5.png)
> 
> I didn't notice the jagged stone displacement at first, but it looks pretty nice and subtle 🙂
> 
> The entrance light looks a bit too blown out, but I do like the look a lot otherwise: ![image](https://user-images.githubusercontent.com/831317/277144747-e1b0865e-fcd3-4931-bab4-6542a7d64b2f.png)
> 
> I like pretty much all of the other lighting you've added 🙂
> 
> I unfortunately can't look through any of the stuff in the quest area. Did you change anything there?

I agree, that area is a bit blown out; I think i know how i can fix it too.

I changed EVERYTHING; Quest area too.

2023-10-22 04:14 UTC, aHooder commented on src/main/java/rs117/hd/data/materials/Material.java
> +	GRUNGE_2_TROLLHEIM_WALL_FIX_2(GRUNGE_2, p -> p.setBrightness(1.2f)),
Presumably Jagex just has different colored variants of it, but I'm not sure. Most likely we can't get a hold of that kind of info, unfortunately. I think we could add some sort of configurable lightness multiplier though

2023-10-22 04:26 UTC, SirFancyBacon commented
![image](https://github.com/117HD/RLHD/assets/11658143/63284501-01b5-4c9b-8d8b-debc54babbd8)

2023-10-22 04:27 UTC, aHooder commented
That looks better. Could it maybe make sense to move the light a bit closer to the bottom of the stairs, and making the radius even wider also?

2023-10-22 05:04 UTC, SirFancyBacon commented
Snow textures and normals improved so they tile better
![image](https://github.com/117HD/RLHD/assets/11658143/57e9eaa9-732e-4986-9d7c-54180e660559)

![image](https://github.com/117HD/RLHD/assets/11658143/e29c43fc-bc68-4e04-8f4e-ed48fafa58b2)

2023-10-22 05:07 UTC, SirFancyBacon commented
> That looks better. Could it maybe make sense to move the light a bit closer to the bottom of the stairs, and making the radius even wider also?

![image](https://github.com/117HD/RLHD/assets/11658143/33e8900f-98ef-4534-8a37-38a56edc4220)

2023-11-05 12:29 UTC, aHooder approved these changes

2023-11-05 14:00 UTC, merged